name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov .
      - name: Upload coverage to Codecov (arg token)
        run: |
          curl -Os https://cli.codecov.io/latest/macos/codecov
          chmod +x codecov
          ./codecov --verbose upload-process -t ${{ secrets.CODECOV_TOKEN }} -n 'service'-${{ github.run_id }} -F service -f coverage-service.xml
